/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package testprogram;

/**
 *
 * @author zfh1005
 */
public class ProgramJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProgramJFrame
     */
    public ProgramJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_DutInfo = new javax.swing.JPanel();
        jLabel_SN = new javax.swing.JLabel();
        jLabel_MAC = new javax.swing.JLabel();
        jLabel_Pin = new javax.swing.JLabel();
        jLabel_SSN = new javax.swing.JLabel();
        jLabelSSID = new javax.swing.JLabel();
        jLabel_PASS = new javax.swing.JLabel();
        jTextField_SN = new javax.swing.JTextField();
        jTextField_MAC = new javax.swing.JTextField();
        jTextField_PIN = new javax.swing.JTextField();
        jTextField_SSN = new javax.swing.JTextField();
        jTextField_SSID = new javax.swing.JTextField();
        jTextField_PASS = new javax.swing.JTextField();
        jLabel_DupIP = new javax.swing.JLabel();
        jTextField_DutIp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_ComList = new javax.swing.JComboBox();
        jLabel_ServerIp = new javax.swing.JLabel();
        jTextField_ServerIp = new javax.swing.JTextField();
        jLabel_PtsIp = new javax.swing.JLabel();
        jTextField_PtsIp = new javax.swing.JTextField();
        jTextField_Station = new javax.swing.JTextField();
        jTextField_ProductName = new javax.swing.JTextField();
        jButton_START = new javax.swing.JButton();
        jButton_QUIT = new javax.swing.JButton();
        jScrollPane_RunInfo = new javax.swing.JScrollPane();
        jTextArea_RunInfo = new javax.swing.JTextArea();
        jTextField_Result = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_Open = new javax.swing.JMenuItem();
        jMenuItem_Save = new javax.swing.JMenuItem();
        jMenuItem_Quit = new javax.swing.JMenuItem();
        jMenu_About = new javax.swing.JMenu();
        jMenuItem_About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_DutInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_SN.setText("SN");

        jLabel_MAC.setText("MAC");

        jLabel_Pin.setText("PIN");

        jLabel_SSN.setText("SSN");

        jLabelSSID.setText("SSID");

        jLabel_PASS.setText("PASS");

        jLabel_DupIP.setText("DUT_IP");

        jLabel1.setText("COM");

        jComboBox_ComList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COM1", "COM2", "COM3", "COM4", "COM5" }));

        jLabel_ServerIp.setText("Server_IP");

        jLabel_PtsIp.setText("PTS_IP");

        javax.swing.GroupLayout jPanel_DutInfoLayout = new javax.swing.GroupLayout(jPanel_DutInfo);
        jPanel_DutInfo.setLayout(jPanel_DutInfoLayout);
        jPanel_DutInfoLayout.setHorizontalGroup(
            jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DutInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_DutInfoLayout.createSequentialGroup()
                        .addComponent(jLabel_SN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_SN, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DutInfoLayout.createSequentialGroup()
                        .addComponent(jLabel_MAC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_MAC, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_DutInfoLayout.createSequentialGroup()
                        .addComponent(jLabel_Pin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_PIN))
                    .addGroup(jPanel_DutInfoLayout.createSequentialGroup()
                        .addComponent(jLabel_SSN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_SSN))
                    .addGroup(jPanel_DutInfoLayout.createSequentialGroup()
                        .addComponent(jLabelSSID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_SSID))
                    .addGroup(jPanel_DutInfoLayout.createSequentialGroup()
                        .addComponent(jLabel_PASS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_PASS)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_DutInfoLayout.createSequentialGroup()
                        .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_DupIP, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_DutIp)
                            .addComponent(jComboBox_ComList, 0, 99, Short.MAX_VALUE)))
                    .addGroup(jPanel_DutInfoLayout.createSequentialGroup()
                        .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_ServerIp)
                            .addComponent(jLabel_PtsIp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_ServerIp)
                            .addComponent(jTextField_PtsIp, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel_DutInfoLayout.setVerticalGroup(
            jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DutInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_SN)
                        .addComponent(jLabel1)
                        .addComponent(jComboBox_ComList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_SN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_MAC)
                    .addComponent(jTextField_MAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Pin)
                    .addComponent(jTextField_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SSN)
                    .addComponent(jTextField_SSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_PtsIp)
                    .addComponent(jTextField_PtsIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSSID)
                    .addComponent(jTextField_SSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ServerIp)
                    .addComponent(jTextField_ServerIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_PASS)
                    .addComponent(jTextField_PASS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_DupIP)
                    .addComponent(jTextField_DutIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField_Station.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jTextField_Station.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Station.setText("PT");
        jTextField_Station.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField_ProductName.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jTextField_ProductName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_ProductName.setText("WGR1100");
        jTextField_ProductName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton_START.setText("START");
        jButton_START.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_START.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_STARTActionPerformed(evt);
            }
        });

        jButton_QUIT.setText("QUIT");
        jButton_QUIT.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_QUIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QUITActionPerformed(evt);
            }
        });

        jScrollPane_RunInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea_RunInfo.setColumns(20);
        jTextArea_RunInfo.setRows(5);
        jScrollPane_RunInfo.setViewportView(jTextArea_RunInfo);

        jTextField_Result.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jTextField_Result.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Result.setText("Standy");
        jTextField_Result.setAutoscrolls(false);
        jTextField_Result.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu_File.setText("File");

        jMenuItem_Open.setText("Open");
        jMenuItem_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_OpenActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_Open);

        jMenuItem_Save.setText("Save");
        jMenuItem_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SaveActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_Save);

        jMenuItem_Quit.setText("Quit");
        jMenuItem_Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_QuitActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_Quit);

        jMenuBar1.add(jMenu_File);

        jMenu_About.setText("About");

        jMenuItem_About.setText("About");
        jMenuItem_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AboutActionPerformed(evt);
            }
        });
        jMenu_About.add(jMenuItem_About);

        jMenuBar1.add(jMenu_About);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane_RunInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jTextField_Station))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_DutInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_ProductName)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton_START, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButton_QUIT, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_Result))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_ProductName)
                    .addComponent(jTextField_Station, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_DutInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_QUIT, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(jButton_START, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane_RunInfo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AboutActionPerformed
        AboutPanel ap = new AboutPanel();
    }//GEN-LAST:event_jMenuItem_AboutActionPerformed

    private void jMenuItem_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_OpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_OpenActionPerformed

    private void jMenuItem_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_SaveActionPerformed

    private void jMenuItem_QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_QuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_QuitActionPerformed

    private void jButton_STARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_STARTActionPerformed
        // TODO add your handling code here:
        
        //run program
    }//GEN-LAST:event_jButton_STARTActionPerformed

    private void jButton_QUITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QUITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_QUITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_QUIT;
    private javax.swing.JButton jButton_START;
    private javax.swing.JComboBox jComboBox_ComList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSSID;
    private javax.swing.JLabel jLabel_DupIP;
    private javax.swing.JLabel jLabel_MAC;
    private javax.swing.JLabel jLabel_PASS;
    private javax.swing.JLabel jLabel_Pin;
    private javax.swing.JLabel jLabel_PtsIp;
    private javax.swing.JLabel jLabel_SN;
    private javax.swing.JLabel jLabel_SSN;
    private javax.swing.JLabel jLabel_ServerIp;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_About;
    private javax.swing.JMenuItem jMenuItem_Open;
    private javax.swing.JMenuItem jMenuItem_Quit;
    private javax.swing.JMenuItem jMenuItem_Save;
    private javax.swing.JMenu jMenu_About;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JPanel jPanel_DutInfo;
    private javax.swing.JScrollPane jScrollPane_RunInfo;
    private javax.swing.JTextArea jTextArea_RunInfo;
    private javax.swing.JTextField jTextField_DutIp;
    private javax.swing.JTextField jTextField_MAC;
    private javax.swing.JTextField jTextField_PASS;
    private javax.swing.JTextField jTextField_PIN;
    private javax.swing.JTextField jTextField_ProductName;
    private javax.swing.JTextField jTextField_PtsIp;
    private javax.swing.JTextField jTextField_Result;
    private javax.swing.JTextField jTextField_SN;
    private javax.swing.JTextField jTextField_SSID;
    private javax.swing.JTextField jTextField_SSN;
    private javax.swing.JTextField jTextField_ServerIp;
    private javax.swing.JTextField jTextField_Station;
    // End of variables declaration//GEN-END:variables
}
